// Squeeze — wat hij zegt en denkt.
// Regels: kort, droog grappig, Engels, kleine letters.
// Nooit: prijsvoorspellingen, "buy now", beloftes of andere coins.
// Invulwoorden: {rings} = aantal ringen, {ring} = nummer van de nieuwe ring,
// {next} = volgende ring, {combo} = combo, {mcap} = marketcap (bv. $50k).
// Nieuwe zinnen toevoegen mag gewoon: zet ze in de juiste lijst.
window.SQUEEZE_LINES = {
  // 💭 als het rustig is
  idle: [
    "counting my rings again. still {rings}.",
    "do octopuses get bored? asking for me.",
    "eight arms and nothing to hold",
    "polishing ring {rings}. it deserves it.",
    "just vibing in the deep",
    "i wonder what the whale is doing",
    "if i had pockets i'd have eight",
    "is green my color? yes.",
    "three hearts. all of them happy.",
    "thinking about ring {next}. just thinking.",
    "the fish never call back",
    "is this ring round enough? yes.",
    "i could juggle. not saying i will.",
    "somewhere a crab is plotting",
    "deep thoughts from the deep",
    "i should name my arms",
    "arm 3 is my favorite. don't tell arm 5.",
    "do rings count as cardio",
    "octopus fact: i am very cute",
    "the ocean is big. i am medium.",
    "wondering if the seal is awake",
    "my ring has a ring to it",
    "floating is a skill",
    "been practicing my smile",
    "sometimes i hug myself. eight times.",
    "ink check: still got it",
    "ocean's quiet. i like it. mostly.",
    "do i look taller today",
    "if you blink i'll wave. maybe.",
    "i'm not round. i'm aerodynamic.",
  ],

  // 💬 eerste buy na een stilte
  firstBuy: [
    "oh. a snack.",
    "someone remembered me 🥹",
    "i felt that. in a good way.",
    "finally, room service",
    "hello? oh hello!",
    "a visitor! tidy the reef!",
    "the silence is broken. nice.",
    "i knew you'd come back",
    "tiny crunch. i'll allow it.",
    "something tasty just arrived",
  ],

  combo3: [
    "ok ok ok",
    "three in a row, nice",
    "this is getting fun",
    "the snacks keep coming",
    "i'm on a roll",
    "rhythm unlocked",
  ],
  combo5: [
    "chewing is hard with this many snacks",
    "my arms can't keep up",
    "x{combo}! is this a party?",
    "nobody told me there was a buffet",
    "five! that's more than my hearts",
    "arms full. heart fuller.",
  ],
  combo10: [
    "I AM THE OCEAN",
    "*burps in green*",
    "x{combo}. i need a moment.",
    "this is too much. i love it.",
    "THE OCEAN IS SHAKING",
    "i can see my house from here",
  ],

  pump: [
    "the water feels warmer",
    "is it me or is everything green today",
    "wheee",
    "my tentacles are tingling",
    "the current is carrying me",
    "i feel lighter",
    "everything's shiny",
    "good vibes in the deep",
  ],
  dump: [
    "i felt that in all 8 arms",
    "who pulled the plug",
    "it's fine. i'm fine. we're fine.",
    "sinking… but gracefully",
    "ow. okay. breathing.",
    "the water got cold",
    "i'll just hug my ring for a bit",
    "not my favorite current",
  ],

  ring: [
    "ring {ring}. i'm basically jewelry now",
    "another one for the collection",
    "this one's shinier. i can tell.",
    "put it on my tab. i have eight arms.",
    "ring {ring}! don't lose it, don't lose it",
    "i earned this one",
    "shiny. mine.",
    "ring {ring}. my collection grows.",
  ],
  reclaim: [
    "told you i'd be back",
    "the comeback octopus",
    "we don't talk about the dip",
    "back on top. arms up.",
    "never doubted it. (i doubted it)",
  ],

  // 💭 in slaap vallen / slapen
  sleep: [
    "wake me when someone's hungry",
    "five more minutes…",
    "zzz… rings… zzz",
    "the ocean got quiet",
    "dreaming of snacks",
    "*snores in bubbles*",
    "resting my arms. all of them.",
    "quiet day in the deep",
  ],
  wake: [
    "WHO FED ME. thank you",
    "i was not sleeping. i was thinking.",
    "huh? oh! hi!",
    "i'm up i'm up",
    "was i snoring?",
    "morning! is it morning?",
  ],

  poke: [
    "that's my face",
    "boop received",
    "careful, i bruise green",
    "you have my attention",
    "hi to you too",
    "tickles",
    "that's not a button",
    "poke acknowledged",
  ],
  annoyed: [
    "i have a ring and i will throw it",
    "ok that's enough poking",
    "i'm telling the crab",
    "personal space. eight arms of it.",
    "do i poke you? no.",
  ],
  highfive: [
    "up top!",
    "eight arms, eight high fives",
    "nailed it",
    "a classic",
    "slap!",
    "we're friends now",
  ],
  glass: [
    "hello? anyone there?",
    "is this thing on?",
    "you've been staring. it's ok. i'm cute.",
    "tap tap. still here?",
    "let me out. kidding.",
    "psst. hi.",
  ],

  // vriendjes
  f_fish: ["oh hey, little guy", "nice fins", "where are you off to?", "swim safe, buddy"],
  f_minnow: ["i have fans now", "a parade! for me?", "so many little friends", "they're spinning. i'm dizzy."],
  f_shrimp: ["tiny friend, big energy", "hop hop hop", "cute little shrimp"],
  f_crabSteal: ["HEY that's MY ring", "give it back!", "not the ring!"],
  f_crabPoke: ["five more minutes, crab", "crab, please.", "i'm awake. barely."],
  f_lobster: ["show-off", "nice claws", "big parade energy", "okay mr. fancy"],
  f_dolphin: ["show me how you do that", "flip!", "i can't jump. i'm too round.", "10/10 flip"],
  f_shark: ["a shark. i'm fine. totally fine.", "don't look. don't look.", "i'm just a rock", "nice teeth. please go."],
  f_seal: ["nap buddy", "scoot over", "sleepy seal club"],
  f_whale: ["that whale just bought the whole ocean", "BIG friend", "whoa. whale.", "the ocean just got smaller"],
  f_jellyDrift: ["jelly's out for a stroll", "hi jelly!", "glowing as always"],

  // marketcap-mijlpaal (samen met de kwal)
  milestone: [
    "{mcap}. not bad for a blob with arms",
    "{mcap}! somebody frame this",
    "{mcap}! jelly came to say hi",
    "{mcap}. i'm telling my mom",
    "party at {mcap}!",
  ],
};
